# Generated by Django 5.2.7 on 2026-02-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0003_micropubrequestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmention',
            name='source',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='webmention',
            name='target',
            field=models.URLField(max_length=2000),
        ),
    ]
