# Generated by Django 5.2.7 on 2026-03-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micropub', '0004_alter_webmention_url_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmention',
            name='is_incoming',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='webmention',
            name='mention_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('reply', 'Reply'), ('repost', 'Repost'), ('like', 'Like'), ('bookmark', 'Bookmark')], default='mention', max_length=16),
        ),
    ]
