# Generated by Django 5.2.7 on 2026-03-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsub', '0002_seed_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='author_url',
            field=models.URLField(blank=True, db_index=True, max_length=2000),
        ),
    ]
