# Generated by Django 5.2.7 on 2025-10-23 16:12

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
