# Generated by Django 5.2.7 on 2025-10-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
