# Generated by Django 5.2.7 on 2025-10-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_menuitem_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['weight']},
        ),
    ]
