# Generated by Django 5.2.7 on 2025-10-23 17:51

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_menuitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=1024)),
                ('bio', markdownx.models.MarkdownxField()),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
