# Generated by Django 5.2.7 on 2025-10-23 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.menu'),
        ),
    ]
