# Generated by Django 5.2.7 on 2025-10-24 15:25

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteconfiguration_main_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='intro',
            field=markdownx.models.MarkdownxField(default='', max_length=512),
        ),
    ]
