# Generated by Django 5.2.7 on 2025-10-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteconfiguration_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=255, null=True, blank=True),
        ),
    ]
