# Generated by Django 5.2.7 on 2025-10-24 16:10

from django.db import migrations
from django.utils.text import slugify

def gen_unique_slug(existing, base):
    slug = base
    i = 2
    while slug in existing:
        slug = f"{base}-{i}"
        i += 1
    return slug

def forwards(apps, schema_editor):
    Page = apps.get_model('core', 'Page')
    # Build a set of current slugs to ensure uniqueness in-memory
    existing = set(
        Page.objects.exclude(slug__isnull=True).exclude(slug__exact='').values_list('slug', flat=True)
    )
    for page in Page.objects.all().only('id', 'title', 'slug'):
        if page.slug:
            existing.add(page.slug)
            continue
        base = slugify(page.title or '') or 'page'
        unique = gen_unique_slug(existing, base)
        Page.objects.filter(pk=page.pk).update(slug=unique)
        existing.add(unique)

def backwards(apps, schema_editor):
    Page = apps.get_model('core', 'Page')
    Page.objects.update(slug=None)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20251024_1608'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
