# Generated by Django 5.2.7 on 2025-10-26 05:38

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bio',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='intro',
            field=mdeditor.fields.MDTextField(default='', max_length=512),
        ),
    ]
