# Generated by Django 5.2.7 on 2025-10-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0012_page_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elsewhere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('profile_url', models.CharField(max_length=1024)),
                ('place', models.CharField(choices=[('x', 'X/Twitter'), ('bsky', 'BSky'), ('email', 'Email'), ('mastodon', 'Mastodon/ActivityPub'), ('github', 'GitHub'), ('instagram', 'Instagram')], default='x', max_length=16)),
            ],
        ),
    ]
