# Generated by Django 5.2.7 on 2025-12-04 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_siteconfigurations', to='core.menu'),
        ),
    ]
