# Generated by Django 5.2.7 on 2025-12-31 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_hcard_photo_asset_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hcardphoto',
            options={'ordering': ['sort_order', 'id']},
        ),
    ]
