# Generated by Django 5.2.7 on 2026-02-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_siteconfiguration_developer_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bridgy_publish_bluesky',
            field=models.BooleanField(default=True, verbose_name='Bridgy Publish: Bluesky'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bridgy_publish_flickr',
            field=models.BooleanField(default=True, verbose_name='Bridgy Publish: Flickr'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bridgy_publish_github',
            field=models.BooleanField(default=True, verbose_name='Bridgy Publish: GitHub'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bridgy_publish_mastodon',
            field=models.BooleanField(default=True, verbose_name='Bridgy Publish: Mastodon'),
        ),
    ]
