# Generated by Django 5.2.7 on 2026-02-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_siteconfiguration_bridgy_publish_bluesky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_gallery',
            field=models.BooleanField(default=False),
        ),
    ]
