# Generated by Django 5.2.7 on 2026-02-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_page_is_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='default_feed_kinds',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of post kinds shown by default when no filter is applied. Leave blank for the default (article, note, photo, activity, event, checkin). Valid values: article, note, photo, activity, like, repost, reply, event, rsvp, checkin, bookmark.', max_length=255),
        ),
    ]
