# Generated by Django 5.2.7 on 2025-12-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='response_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
