# Generated by Django 5.2.7 on 2025-12-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_visit_response_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='user_agent_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
