# Generated by Django 5.2.7 on 2025-10-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_on',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
