# Generated by Django 5.2.7 on 2026-02-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_comment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='blog_commen_status_74f07c_idx',
            old_name='blog_comment_status_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='blog_commen_created_4e025c_idx',
            old_name='blog_comment_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='blog_commen_post_id_fe6079_idx',
            old_name='blog_comment_post_idx',
        ),
    ]
