# Generated by Django 5.2.7 on 2026-02-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_rename_blog_comment_status_idx_blog_commen_status_74f07c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('article', 'Article'), ('note', 'Note'), ('photo', 'Photo'), ('activity', 'Activity'), ('like', 'Like'), ('repost', 'Repost'), ('reply', 'Reply'), ('event', 'Event'), ('rsvp', 'RSVP'), ('checkin', 'Check-in')], default='article', max_length=16),
        ),
    ]
