# Generated by Django 5.2.7 on 2026-02-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_add_event_rsvp_checkin_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmark_of',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('article', 'Article'), ('note', 'Note'), ('photo', 'Photo'), ('activity', 'Activity'), ('like', 'Like'), ('repost', 'Repost'), ('reply', 'Reply'), ('event', 'Event'), ('rsvp', 'RSVP'), ('checkin', 'Check-in'), ('bookmark', 'Bookmark')], default='article', max_length=16),
        ),
    ]
