# Generated by Django 5.2.7 on 2026-02-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indieauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndieAuthRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('error', models.TextField(blank=True)),
                ('request_headers', models.JSONField(default=dict)),
                ('request_query', models.JSONField(default=dict)),
                ('request_body', models.TextField(blank=True)),
                ('response_body', models.TextField(blank=True)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
